version: '3.8'
services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db:5432/mydatabase"
      PYTHONPATH: "/app"
